create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text unique not null,
  name text default '',
  role text not null default 'CUSTOMER' check (role in ('CUSTOMER', 'MANAGEMENT')),
  created_at timestamptz not null default timezone('utc', now())
);

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, role)
  values (new.id, new.email, 'CUSTOMER')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

create table if not exists public.room_inventory (
  id uuid primary key default gen_random_uuid(),
  room_code text unique not null,
  floor integer not null check (floor between 1 and 5),
  room_type text not null,
  bed_size text not null,
  has_balcony boolean not null default false,
  has_pool boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.table_inventory (
  id uuid primary key default gen_random_uuid(),
  table_code text unique not null,
  floor integer not null check (floor between 1 and 5),
  seats integer not null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.room_bookings (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references public.profiles (id) on delete cascade,
  customer_email text not null,
  customer_name text not null,
  name text not null,
  age integer,
  contact text not null,
  address text not null,
  id_proof text not null,
  room_type text not null,
  bed_size text not null,
  floor integer not null check (floor between 1 and 5),
  balcony boolean not null default false,
  pool boolean not null default false,
  price integer not null,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'cancelled')),
  assigned_room_id uuid references public.room_inventory (id),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.table_bookings (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references public.profiles (id) on delete cascade,
  customer_email text not null,
  customer_name text not null,
  name text not null,
  age integer,
  contact text not null,
  floor integer not null check (floor between 1 and 5),
  seats integer not null,
  price integer not null,
  status text not null default 'pending' check (status in ('pending', 'accepted', 'cancelled')),
  assigned_table_id uuid references public.table_inventory (id),
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.management_users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  email text unique,
  password text not null,
  name text not null,
  role text not null default 'MANAGEMENT'
);

alter table public.profiles enable row level security;
alter table public.room_inventory enable row level security;
alter table public.table_inventory enable row level security;
alter table public.room_bookings enable row level security;
alter table public.table_bookings enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles
for select to authenticated
using (auth.uid() = id);

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles
for update to authenticated
using (auth.uid() = id)
with check (auth.uid() = id and role = 'CUSTOMER');

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles
for insert to authenticated
with check (auth.uid() = id and role = 'CUSTOMER');

drop policy if exists "inventory_read_room" on public.room_inventory;
create policy "inventory_read_room" on public.room_inventory
for select to authenticated
using (true);

drop policy if exists "inventory_read_table" on public.table_inventory;
create policy "inventory_read_table" on public.table_inventory
for select to authenticated
using (true);

drop policy if exists "room_bookings_select_own" on public.room_bookings;
create policy "room_bookings_select_own" on public.room_bookings
for select to authenticated
using (auth.uid() = customer_id);

drop policy if exists "room_bookings_insert_own" on public.room_bookings;
create policy "room_bookings_insert_own" on public.room_bookings
for insert to authenticated
with check (auth.uid() = customer_id);

drop policy if exists "table_bookings_select_own" on public.table_bookings;
create policy "table_bookings_select_own" on public.table_bookings
for select to authenticated
using (auth.uid() = customer_id);

drop policy if exists "table_bookings_insert_own" on public.table_bookings;
create policy "table_bookings_insert_own" on public.table_bookings
for insert to authenticated
with check (auth.uid() = customer_id);

insert into public.room_inventory (room_code, floor, room_type, bed_size, has_balcony, has_pool)
values
  ('F1-R101', 1, 'Single', 'Twin', false, false),
  ('F1-R102', 1, 'Double', 'Queen', false, false),
  ('F2-R201', 2, 'Double', 'King', true, false),
  ('F2-R202', 2, 'Triple', 'Queen', true, false),
  ('F3-R301', 3, 'Double', 'King', true, true),
  ('F3-R302', 3, 'Quad', 'King', true, true),
  ('F4-R401', 4, 'Triple', 'Queen', true, true),
  ('F5-R501', 5, 'Quad', 'King', true, true)
on conflict (room_code) do nothing;

insert into public.table_inventory (table_code, floor, seats)
values
  ('F1-T01', 1, 2),
  ('F1-T02', 1, 4),
  ('F2-T01', 2, 4),
  ('F2-T02', 2, 10),
  ('F3-T01', 3, 2),
  ('F3-T02', 3, 20),
  ('F4-T01', 4, 4),
  ('F5-T01', 5, 10)
on conflict (table_code) do nothing;
